/* eslint-disable no-unused-vars */
import Head from 'next/head'
import { useAccount, useProvider } from 'wagmi';
import styles from '../styles/Home.module.css';
import { NextPage } from 'next';
import MoneyStreamerFlows from '../components/MoneyStreamerFlows';

const Home: NextPage = () => {
  const { address, isConnecting, isDisconnected, isConnected } = useAccount();
  const provider = useProvider();


  return (
    <div className={styles.container}>
      <Head>
        <title>Money streamer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isConnected &&
        <>
          <MoneyStreamerFlows />
        </>
      }

      {!isConnected &&
        <h1>Disconnected</h1>
      }


    </div>
  )
}

export default Home;