/* eslint-disable no-unused-vars */
import Head from 'next/head'
import Image from 'next/image'
import { useAccount, useProvider } from 'wagmi';
import styles from '../styles/Home.module.css';
import { MoneyRouter } from '../../typechain-types/contracts/MoneyRouter';
import { ethers } from "ethers";
import { NextPage } from 'next';
import MoneyStreamerInteraction from '../components/MoneyStreamerInteraction';

//import { useAccount, useConnect, useDisconnect } from 'wagmi'
//import { InjectedConnector } from 'wagmi/connectors/injected'

const Home: NextPage = () => {
  const { address, isConnecting, isDisconnected, isConnected } = useAccount();
  const provider = useProvider();


  return (
    <div className={styles.container}>
      <Head>
        <title>Money streamer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isConnected &&
        <>
          <h1>Connected</h1>
          <br />
          <MoneyStreamerInteraction />
        </>
      }

      {!isConnected &&
        <h1>Disconnected</h1>
      }



      {/*isConnected &&

        <>
          <Input placeholder="default size" prefix={<UserOutlined />} value={recipient} onChange={(e) => setRecipient(e.target.value)} />
          <InputNumber addonBefore="Wei per sec" min={1} value={amountWeiPerSec} onChange={(value) => setAmountWeiPerSec(value ?? 0)} />
          <Divider />

          <Button shape='round' type="primary" onClick={createFlow}>Create flow</Button>
          <Button shape='round' type="primary" onClick={deleteFlow}>Delete flow</Button>
          <Button shape='round' type="primary" onClick={updateFlow}>Update flow</Button>
          <Button shape='round' type="primary" onClick={fetchStreams}>Update streams</Button>

          <Table columns={columns} dataSource={streams} />

  </>*/}

    </div>
  )
}

export default Home;